"""create equipment table

Revision ID: 66603d461caa
Revises:
Create Date: 2026-08-11 17:42:04.511830

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66603d461caa"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "equipment",
        sa.Column("equipment_id", sa.String(length=64), nullable=False),
        sa.Column("equipment_type", sa.String(length=50), nullable=False),
        sa.CheckConstraint(
            "length(btrim(equipment_id)) > 0",
            name="ck_equipment_equipment_id_not_blank",
        ),
        sa.PrimaryKeyConstraint("equipment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("equipment")
    # ### end Alembic commands ###
