"""add process runs and alarm events

Revision ID: 7939004569c4
Revises: a695b7aaf302
Create Date: 2026-08-11 18:02:10.911009

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7939004569c4"
down_revision: Union[str, Sequence[str], None] = "a695b7aaf302"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alarm_event",
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("equipment_id", sa.String(length=64), nullable=False),
        sa.Column("alarm_code", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "cleared_at IS NULL OR cleared_at >= occurred_at",
            name="ck_alarm_event_time_order",
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"], ["equipment.equipment_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_alarm_event_code_occurred_at",
        "alarm_event",
        ["alarm_code", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_alarm_event_equipment_occurred_at",
        "alarm_event",
        ["equipment_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "process_run",
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("equipment_id", sa.String(length=64), nullable=False),
        sa.Column("lot_id", sa.String(length=64), nullable=False),
        sa.Column("recipe", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("yield_rate", sa.Numeric(precision=6, scale=5), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at > started_at",
            name="ck_process_run_time_order",
        ),
        sa.CheckConstraint(
            "yield_rate IS NULL OR (yield_rate >= 0 AND yield_rate <= 1)",
            name="ck_process_run_yield_rate_range",
        ),
        sa.ForeignKeyConstraint(
            ["equipment_id"], ["equipment.equipment_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        "ix_process_run_equipment_started_at",
        "process_run",
        ["equipment_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_process_run_lot_id"), "process_run", ["lot_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_process_run_lot_id"), table_name="process_run")
    op.drop_index("ix_process_run_equipment_started_at", table_name="process_run")
    op.drop_table("process_run")
    op.drop_index("ix_alarm_event_equipment_occurred_at", table_name="alarm_event")
    op.drop_index("ix_alarm_event_code_occurred_at", table_name="alarm_event")
    op.drop_table("alarm_event")
    # ### end Alembic commands ###
