"""add hybrid knowledge search

Revision ID: a695b7aaf302
Revises: 66603d461caa
Create Date: 2026-08-11 17:55:40.912624

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import VECTOR
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a695b7aaf302"
down_revision: Union[str, Sequence[str], None] = "66603d461caa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A clean database does not run the local Docker initialization scripts.
    # Create the extension here before PostgreSQL sees the VECTOR column type.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_document",
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("equipment_type", sa.String(length=50), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=500), nullable=False),
        sa.Column("embedding", VECTOR(dim=1536), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(content, ''))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(btrim(content)) > 0", name="ck_knowledge_document_content_not_blank"
        ),
        sa.CheckConstraint(
            "length(btrim(document_id)) > 0", name="ck_knowledge_document_id_not_blank"
        ),
        sa.CheckConstraint(
            "length(btrim(title)) > 0", name="ck_knowledge_document_title_not_blank"
        ),
        sa.PrimaryKeyConstraint("document_id"),
    )
    op.create_index(
        "ix_knowledge_document_embedding_hnsw",
        "knowledge_document",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_knowledge_document_equipment_type"),
        "knowledge_document",
        ["equipment_type"],
        unique=False,
    )
    op.create_index(
        "ix_knowledge_document_search_vector",
        "knowledge_document",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_knowledge_document_search_vector",
        table_name="knowledge_document",
        postgresql_using="gin",
    )
    op.drop_index(
        op.f("ix_knowledge_document_equipment_type"), table_name="knowledge_document"
    )
    op.drop_index(
        "ix_knowledge_document_embedding_hnsw",
        table_name="knowledge_document",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("knowledge_document")
    # ### end Alembic commands ###
