"""add maintenance approvals

Revision ID: d51a31dabd71
Revises: 7939004569c4
Create Date: 2026-08-11 18:13:50.241586

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d51a31dabd71"
down_revision: Union[str, Sequence[str], None] = "7939004569c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "approval_request",
        sa.Column("approval_id", sa.String(length=36), nullable=False),
        sa.Column("equipment_id", sa.String(length=64), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_by", sa.String(length=100), nullable=True),
        sa.Column("decision_note", sa.String(length=1000), nullable=True),
        sa.ForeignKeyConstraint(
            ["equipment_id"], ["equipment.equipment_id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("approval_id"),
    )
    op.create_index(
        "ix_approval_request_status_requested_at",
        "approval_request",
        ["status", "requested_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_approval_request_status_requested_at", table_name="approval_request"
    )
    op.drop_table("approval_request")
    # ### end Alembic commands ###
